project:
  type: book
  output-dir: docs

book:
  title: "Pythoneer"
  author: "Edgar Treischl"
  date: last-modified
  chapters:
    - index.qmd
    - firststeps.qmd
    - manipulation.qmd
    - visualization.qmd
    - references.qmd
  navbar:
    right:
      - icon: github
        href: https://github.com/edgar-treischl/Pythoneer
        aria-label: GitHub

cover-image: cover.jpeg
bibliography: references.bib

format:
  html:
    theme: litera
    include-in-header: 
      - progress-bar.html
  pdf:
    documentclass: book
    highlight-style: kate



