project:
  type: book
  output-dir: docs

book:
  title: "Pythoneer"
  author: "Edgar Treischl"
  date: "3/19/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - firststeps.qmd
    - manipulation.qmd
    - visualization.qmd
    - references.qmd

cover-image: cover.jpeg
bibliography: references.bib

format:
  html:
    theme: litera
  pdf:
    documentclass: book
    highlight-style: kate



